### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by pugliathomas** [gbrueckl/PowerBI-VSCode#1]
hello, I am looking for the VSIX but cannot find it. can I build from this repo?

**Comment by gbrueckl** [comment]
you can always download the latest [published] VSIX directly from the VSCode Gallery
https://marketplace.visualstudio.com/items?itemName=GerhardBrueckl.powerbi-vscode
just click the "Download Extension" link

regarding building from the repo:
you need to make sure you have installed NodeJS https://nodejs.org/en/
then open the repo in VSCode and run `npm install` which will install all dependencies
pressing F5 will run the extension in debug mode where you can use break-points etc.
to generate the `.vsix`, you need to run `vsce package` in the terminal

**Comment by samaguire** [comment]
@gbrueckl Nice work! I see this as a very promising addon. 👏

![image](https://media.giphy.com/media/J0IFnuXpYQIcnWD5v1/giphy.gif)

You should add the market link to your repo readme.

Also, do you have any details on functionality? i.e. it looks like i can't add myself as an Admin to a workspace, but i can take over a dataset...

Are there any rules around contributing to this project? I'm looking at building a PowerShell notebook to recover an undownloadable report (i.e. created online), but it looks like this tool could do that sort of thing as well - I'd consider adding that as a feature to this as well.

**Comment by gbrueckl** [comment]
@samaguire the extension is design to potentially support any API call but obviously this is currently not the case.
there are quite some limitations in VSCode when it comes to input some data necessary for an API call (e.g. VSCode only has a native text-input control and a dropdown control)
I tried to work around those limitations by enabling drag&drop which works fine already
e.g. drag a report onto a dataset to rebind it etc.

I am happy for any contributions  - but I think I need to write some proper documentation first :) 

your solution for downloading online-reports should definitely be doable, as as I understood it, its just a set of API calls (copyContent, download, ...)

**Comment by gbrueckl** [comment]
I just ran a quick test and it seems like you can now regularly download reports that were only created online
could you please verify again if this is still an issue?

I will also add an option to Download a report from the extension in the next releasea

**Comment by samaguire** [comment]
> I just ran a quick test and it seems like you can now regularly download reports that were only created online could you please verify again if this is still an issue?
> 
> I will also add an option to Download a report from the extension in the next releasea

I haven't had this as an issue for some time now. Probably not an issue now. Looking forward to the next version

**Comment by gbrueckl** [comment]
ok, great, closing this issue then
