### ISSUE TITLE
Cannot Open Notebook

### ISSUE THREAD

**Issue by tarektm17** [gbrueckl/PowerBI-VSCode#10]
Hi Gerhard,

Thanks for the PBI-VSCode ext.
I'm facing an issue whenever I try to open a notebook.
I'm using the latest version 0.9.7
The Message is:
Command 'PowerBI: Open new Power BI Notebook' resulted in an error
Cannot read properties of undefined (reading 'apiPath')

How to resolve this?

Thanks

**Comment by gbrueckl** [comment]
thanks for reporting

I found the issue and fixed it with 0.9.8 which is live now

**Comment by tarektm17** [comment]
Thanks mate

**Comment by gbrueckl** [comment]
closed as fixed
