### ISSUE TITLE
Way too easy to delete objects by mistake

### ISSUE THREAD

**Issue by F-Bastiat** [gbrueckl/PowerBI-VSCode#11]
Thank you for the work put into this, it has great potential. But for now I'm actually scared to even try out the extension.

Suggesting to remove the "delete / unassign from capacity" buttons from the inline context and hide them behind a right-click context menu or something similar, and also to add a confirmation window.

**Comment by gbrueckl** [comment]
good points!
will hide/move the buttons and add another confirmation for sensitive operations/commands

**Comment by gbrueckl** [comment]
this change is also part of the prelease-v1.0.0
https://github.com/gbrueckl/PowerBI-VSCode/releases/tag/v1.0.0-prerelease

you can install it manually and test if it works better for you now.
There are two ways for confirmation - a simple Yes/No selection or a textbox where you need to enter the name of e.g. the workspace again to unassign it

**Comment by gbrueckl** [comment]
this has been fixed with v1.0.0
