### ISSUE TITLE
Workspace Browser: Dataflows without names

### ISSUE THREAD

**Issue by FrankPreusker** [gbrueckl/PowerBI-VSCode#13]
The workspace browser does show non-existing dataflows (only GUID, no name).

**Comment by gbrueckl** [comment]
from my experience those are from Fabric and are generated in the background
as of now, we simply call the API and show the results

we will consider removing the dataflows without a name though

**Comment by FrankPreusker** [comment]
I would probably vote for "removing" if they don't have any real purpose (and nobody outside of MS should actually deal with them).

**Comment by gbrueckl** [comment]
closing as fixed
