### ISSUE TITLE
Workspace Browser enhancement request: copy object name and/or GUID

### ISSUE THREAD

**Issue by FrankPreusker** [gbrueckl/PowerBI-VSCode#14]
It would be very useful to copy any object name (eg workspace, dataset, report, etc) and/or object GUID from the workspace browser list.

**Comment by gbrueckl** [comment]
there is the `Insert Path` button next to each item in the workspace browser which adds the full API path of that item to the currently open editor/notebook
isn't that sufficient?

**Comment by FrankPreusker** [comment]
Got it. I have previously clicked on that icon, but didn't had any open file (and hence nothing happened). Might be better to copy it to the clipboard instead.

**Comment by gbrueckl** [comment]
I had a discussion about this with someone from the VSCode team and they had a good reason not to use the clipboard - i canst cant remember it anymore nor find the discussion :D

**Comment by gbrueckl** [comment]
how about this:
![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/11884402/5beafd86-86b2-42ca-8ba8-ba97a8766eba)

**Comment by FrankPreusker** [comment]
Looks good. Can you keep the name "Clibpoard" 😁

**Comment by gbrueckl** [comment]
will include this with the next release then

**Comment by gbrueckl** [comment]
this has just been released with `v1.1.0`

**Comment by gbrueckl** [comment]
closing as fixed
