### ISSUE TITLE
Workspace Browser enhancement: support for all Fabric artefacts

### ISSUE THREAD

**Issue by FrankPreusker** [gbrueckl/PowerBI-VSCode#15]
Currently we get Datasets, Reports, Dashboards & Dataflows from the workspace browser. Can the new Fabric artefacts like Lakehouse, Warehouse, Notebooks, Pipelines, etc be added here as well?

**Comment by gbrueckl** [comment]
Once we have the necessary APIs available, definitely yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Frank Preusker ***@***.***>
Sent: Monday, October 30, 2023 5:04:46 PM
To: gbrueckl/PowerBI-VSCode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gbrueckl/PowerBI-VSCode] Workspace Browser enhancement: support for all Fabric artefacts (Issue #15)


Currently we get Datasets, Reports, Dashboards & Dataflows from the workspace browser. Can the new Fabric artefacts like Lakehouse, Warehouse, Notebooks, Pipelines, etc be added here as well?

**Comment by gbrueckl** [comment]
please check out the new Fabric integration that was released with `v1.5.0` today
https://github.com/gbrueckl/PowerBI-VSCode/tree/v1.5.0?tab=readme-ov-file#microsoft-fabric

as of now it only shows items that also support the [GetDefinition APIs](https://learn.microsoft.com/en-us/rest/api/fabric/core/items/get-item-definition?tabs=HTTP): [Supported Item Types](https://learn.microsoft.com/en-us/rest/api/fabric/articles/item-management/definitions/item-definition-overview#definition-details-for-supported-item-types)

let me know what you think!

**Comment by samaguire** [comment]
I've added the json to my workspace settings file, but it doesn't seem to be doing anything. Am I missing something?

![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/62320770/c34b8330-6233-4b2a-8597-e9cea90a6dd2)

**Comment by gbrueckl** [comment]
the folder will show up in the VSCode Explorer and not under the Power BI Tab.
It is implemented as Custom File System so you can then work with the Fabric Items as if they were regular items on your local disk

**Comment by samaguire** [comment]
I checked the folders, nothing there. It looks like the settings aren't valid - based on the message i get when i hover over the json in the settings file.

![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/62320770/97b43ec5-711c-4305-874f-3aeb88f190ae)

**Comment by samaguire** [comment]
That worked. Cheers!

**Comment by gbrueckl** [comment]
feedback is appreciated :) 
for now you can load/modify/publish all Fabric items that support the Get Definition API (Notebooks, Datasets, Reports, Spark Jobs)

**Comment by samaguire** [comment]
Awesome feature! Would it be possible to have the notebooks as ipynb files instead of py files?

**Comment by gbrueckl** [comment]
There is a config setting, yes
https://github.com/gbrueckl/PowerBI-VSCode?tab=readme-ov-file#configuration

But there is currently no way to execute the notebook against the Fabric cluster - working on this though

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gbrueckl** [comment]
most of this was moved to my [Fabric Studio extension](https://marketplace.visualstudio.com/items?itemName=GerhardBrueckl.fabricstudio)
closing this issue
