### ISSUE TITLE
Connecting to GCC

### ISSUE THREAD

**Issue by mabaugh83** [gbrueckl/PowerBI-VSCode#18]
when connecting to commercial everything works fine.
When trying to connect to GCC I either get 
This page isn’t working right nowIf the problem continues, contact the site owner.
HTTP ERROR 400

or 
http://127.0.0.1:57500/callback?nonce=JskRe2ULsAv3MxwWvMEhWA%3D%3D&error=invalid_client&error_description=AADSTS650057%3A+Invalid+resource.+The+client+has+requested+access+to+a+resource+which+is+not+listed+in+the+requested+permissions+in+the+client%27s+application+registration.+Client+app+ID%3A+e56eca75-b688-4b21-a72d-557d10d015cb%28OPPD-PowerBI+Helper%29.+Resource+value+from+request%3A+https%3A%2F%2Fanalysis.usgovcloudapi.net%2Fpowerbi%2Fapi.+Resource+app+ID%3A+fc4979e5-0aa5-429f-b13a-5d1365be5566.+List+of+valid+resources+from+app+registration%3A+00000009-0000-0000-c000-000000000000%2C+00000002-0000-0000-c000-000000000000.+Trace+ID%3A+726a989c-fb71-4e38-85a8-fa676b6c0500+Correlation+ID%3A+5781d63b-3b94-459b-823e-71f2bb11b4ab+Timestamp%3A+2023-10-30+20%3A51%3A58Z&state=http%3A%2F%2F127.0.0.1%3A57500%2Fcallback%3Fnonce%3DJskRe2ULsAv3MxwWvMEhWA%253D%253D

Any thoughts?

Also once i get connected is there a way to query the tenant settings for power bi?

**Comment by gbrueckl** [comment]
in general, GCC should work, at least for everything except the TMDL integration which is not yet tested with GCC
the only thing you need to do is to set the `powerbi.cloud` config to your type of Azure Cloud

did you us a custom client Id via `powerbi.clientId`? if yes, make sure it has the required permissions like `Workspace.Read.All` etc.

**Comment by gbrueckl** [comment]
closing as no further information was provided
