### ISSUE TITLE
feature request - workspace browser - workspace search

### ISSUE THREAD

**Issue by savoy9** [gbrueckl/PowerBI-VSCode#21]
I have access to hundreds of workspaces. I would love to see a little search/filter box for the workspace list. Even better would be to respect the pins i have in the PBI service, but I doubt that data is available to you.

**Comment by savoy9** [comment]
CtrlF is probably plenty. Good to know.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gbrueckl** [comment]
it comes out-of-the-box with every treeview/browser in VSCode :)

**Comment by gbrueckl** [comment]
closing this as fixe :)
