### ISSUE TITLE
Filter functionality in the browse section

### ISSUE THREAD

**Issue by jianchen1628** [gbrueckl/PowerBI-VSCode#23]
Great tool to write your code on vscode as an alternative to the UI. 
Regarding this CR, it would be great if there is some kind of filter option in the browse section.
E.g. I'm one of many Databricks user on a regular base in my company, thus we have a quite a lot workspaces and cluters. 
Having the functionality to filter, or considering the cluster section to choose the clusters I'm assigned to would ease the work quite a lot!

**Comment by gbrueckl** [comment]
I think you wanted to open this issue in the Databricks-VSCode repo :)
https://github.com/paiqo/Databricks-VSCode/issues

happy to answer your questions there
