### ISSUE TITLE
Unable to read notebooks via %run command

### ISSUE THREAD

**Issue by jianchen1628** [gbrueckl/PowerBI-VSCode#24]
Hi, it seems that the current IDE lacks in handling linebreaks, i.e. if I run an underlying notebook within a cell using `%run`. 
![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/154610187/b0c85a4a-833e-4757-be77-87a906af697e)
![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/154610187/35b81e9e-232d-4e6c-8eab-822daa841478)
![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/154610187/0f9770c1-ff2f-47e5-906d-f833f498bc5c)

However, this works absolutely fine, if I run the Notebook directly or via Databricks UI.

**Comment by gbrueckl** [comment]
please open this issue in https://github.com/paiqo/Databricks-VSCode/issues
