### ISSUE TITLE
Unable to connect to use the extension

### ISSUE THREAD

**Issue by atonkyn** [gbrueckl/PowerBI-VSCode#26]
Hi there, I can’t resolve the message…

_Please log in to VSCode with a Microsoft Account first!
See blue badge at the bottom of the activity bar on the left_

Shows as...
![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/17517749/88423c80-e5fa-46df-a393-843d477e4136)

- I’m logged in with a Microsoft account under Accounts
- I have a dark blue “shield” badge at the bottom left of the status bar, below the activity bar, this takes me to “Workspace Trust” and I have “In a Trusted Workspace” selected
- Settings are as follows.. 
![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/17517749/0fb644cc-d36a-4a5a-bced-04c827b48829)

What do I need to do?

**Comment by gbrueckl** [comment]
looks like you have an outdated version - the UI should look like this and you should get prompted automatically for login the first time (or if you have not yet logged in successfully)
![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/11884402/69a9da2d-9573-4c29-9470-b106d79ed275)

can you please check and make sure you are using the latest version `v1.6.3`

**Comment by gbrueckl** [comment]
any feedback on this @atonkyn?
otherwise I would close this issue
