### ISSUE TITLE
Add "Refresh Semantic Model - Yes/No" option when using deployment pipelines

### ISSUE THREAD

**Issue by Lvanlaar26** [gbrueckl/PowerBI-VSCode#29]
Love that you have the option to stage an App update after successful deployment. In the same way, it would be awesome to also get a yes/no option for triggering a full refresh of the model in the destination workspace after successful promotion via deployment pipelines.

**Comment by gbrueckl** [comment]
opposed to updating the App, refreshing all deployed datasets is not supported/no feature out of the box via the Deployment pipelines API 

technically i could give you a dropdown (multiselect) where you could select the datasets that you want to refresh after the deployment. 
BUT the deployment is asynchronous and I dont know when it is finished and obviously it only makes sense to trigger the refresh once the deployment is done

so ideally this would be a part of the official REST API but I do not think this will be added 

I will keep this idea in the backlog but dont expect it to be implemented soon

**Comment by Lvanlaar26** [comment]
I had assumed the existing deployment option was alright sequencing several REST API requests to deploy and update the app, but sounds like the complexity to add this would be more than its worth. Totally agree with your assessment. Thanks!

**Comment by gbrueckl** [comment]
will close this issue then
