### ISSUE TITLE
Pipelines section in sidebar won't load/refresh

### ISSUE THREAD

**Issue by JamesDBartlett3** [gbrueckl/PowerBI-VSCode#3]
Toast notification:

> Refreshing Pipelines... Source: Power BI VSCode (Extension)

Toast error message: 

> Cannot read properties of undefined (reading 'toString')

![image](https://user-images.githubusercontent.com/37491308/212975695-b3cee60a-9ec7-4134-9809-f89ce485f3d7.png)

The Workspaces, Capacities, and Gateways sections all populate as expected, but the Pipelines section still insists that I'm not signed into VSCode:

![image](https://user-images.githubusercontent.com/37491308/212976460-d43983b4-f4fa-4a51-9afe-41fc54891e62.png)

My Power BI tenant has several active deployment pipelines, and I have verified that they are visible to the Power BI REST API by querying the [GetPipelinesAsAdmin](https://learn.microsoft.com/en-us/rest/api/power-bi/admin/pipelines-get-pipelines-as-admin) endpoint:

![image](https://user-images.githubusercontent.com/37491308/212978101-73b1b6e5-6d86-4804-9e8b-55ca522494fa.png)

I've also replicated this issue in both VSCode Desktop and VSCode.dev, both running the latest version of the Power BI VSCode extension (v0.3.0 as of this writing) and logged-in with the same Microsoft account that I used to run the API query in the screenshot above.

Please let me know if I can assist you in tracking down and solving this problem.

**Comment by gbrueckl** [comment]
we are currently not using the Admin APIs but the regular ones. E.g. to get the pipelines we use https://learn.microsoft.com/en-us/rest/api/power-bi/pipelines/get-pipeline
this would be the actual code

could it be that you are an admin user which is not directly assigned to any pipeline? 

I was not yet sure how to integrate the Admin-APIs - these options came to my mind:
- separate treeviews
- global parameter (VSCode setting) to always use the Admin APIs (or not)

what do you think?

**Comment by JamesDBartlett3** [comment]
> could it be that you are an admin user which is not directly assigned to any pipeline?

I just queried the [non-admin Get Pipelines endpoint](https://learn.microsoft.com/en-us/rest/api/power-bi/pipelines/get-pipelines) using the same account, and it returned the same results, so it's not simply a matter of admin vs. non-admin API. Too bad, because that would have been a really easy fix! 

> what do you think?

Great question! I think a "separate treeviews" implementation (or something similar) would offer a much more intuitive, streamlined UX than a hard-coded switch buried somewhere in VS Code's `settings.json` file. I've been using VS Code for 4+ years, I love using extensions, and even though I'm a pretty technically savvy guy, I still really dislike awkwardly stumbling through a configfile just to change a basic setting, while desperately hoping that I don't accidentally break everything with a misplaced semicolon or quotation mark (and if that sounds like an exaggeration, I promise that it's not). 

I know the "global parameter" implementation would be much simpler to implement, but part of the reason I'm so excited about your Power BI VSCode extension is that it makes working with Power BI's REST APIs so easy that even non-technical people could do it. Power BI itself has made BI and DA accessible and fun for laypeople, and I think your extension will do the same thing with Power BI's REST APIs, as long as the UI remains simple, intuitive, and user-friendly.

I'd be happy to chip in and help with this, by the way. I probably can't do the actual coding myself, but I can certainly help with testing, and I'm also pretty decent at writing documentation. Let me know!

**Comment by gbrueckl** [comment]
i just had another look at the Admin APIs and it seems not all endpoints also exist in the Admin APIs which makes the decision easier for me on how to implement it - we need to go for separate TreeViews! (and no global configuration)

regarding your issue, can you please check the output channel to see whats returned when the API is called?
![image](https://user-images.githubusercontent.com/11884402/213123854-31250d1d-2f63-4cf4-b7e3-9ba6078a8746.png)
(thats for my tenant where it is working)

regarding contributions - happy for any support here :)
PS: it is also quite easy to set the coding up in your environment as described here https://github.com/gbrueckl/PowerBI-VSCode#building-locally

**Comment by JamesDBartlett3** [comment]
I just upgraded to `v0.4.0`, then restarted VS Code and tried again. Same issue. I checked the Output window, and all of the expected responses are there except for the Pipelines. Very strange.

**Comment by gbrueckl** [comment]
can you share the returned JSON?

**Comment by JamesDBartlett3** [comment]
I just cleared the output and tried again, and this time, the Pipelines **_do_** appear in the JSON output, but the Pipelines section in the sidebar still says "Please log in to VSCode with a Microsoft Account first!"
![image](https://user-images.githubusercontent.com/37491308/213242337-bf83b180-33a2-4aff-8412-fdb155047f72.png)

**Comment by gbrueckl** [comment]
v0.4.1 is published and should fix the issue :)

**Comment by JamesDBartlett3** [comment]
I can confirm, that fixed it! Thanks!
