### ISSUE TITLE
Issue with Find (CTRL-F) in the Deployment Pipelines section?

### ISSUE THREAD

**Issue by edhans** [gbrueckl/PowerBI-VSCode#30]
Is there an issue with the latest update and CTRL-F not working (find) to filter datasets and reports in the Deployment Pipelines section? this image is what it used to look like for me:
![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/45298358/e1a157b7-e0ee-4b87-89ff-fd4b312b8782)

Pressing CTRL-F does nothing, and Find/Replace are grayed out in the Edit menu. I have restarted VS Code and even rebooted the PC. Still doesn't work.

The Find/Replace keyboard shortcuts and features work fine when editing a document, just no longer with this addin.

**Comment by gbrueckl** [comment]
Hey @edhans,

that is nothing related to the extension itself but a change recently introduced in VSCode which has an impact on all treeviews like the ones I am using. It is described here with a potential workaround
https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding

regards,
-gerhard
