### ISSUE TITLE
Error in notebooks: TypeError: Cannot read properties of undefined (reading 'variables')

### ISSUE THREAD

**Issue by mdieperink** [gbrueckl/PowerBI-VSCode#31]
Every attempt at an api call in a pbinb gives the same error:
`TypeError: Cannot read properties of undefined (reading 'variables')`

**Comment by mdieperink** [comment]
I suspect it has something to do with the last update of the Azure Account I installed today, but I'm not sure.

**Comment by gbrueckl** [comment]
does it work in general - e.g. if you create a new Notebook from scratch?

**Comment by mdieperink** [comment]
ah, a new Notebook from scratch DID work. After I restarted vscode the Notebook that gave an error also worked again. I should have tried that earlier. Sorry to bother you :)

**Comment by gbrueckl** [comment]
no worries :)
