### ISSUE TITLE
CTRL + F treeview search is not working

### ISSUE THREAD

**Issue by johnst101** [gbrueckl/PowerBI-VSCode#32]
The ability to use `CTRL + F` to search within the treeviews seems to be broken. When I select a treeview to search in both the 'Workspaces' section as well as the 'Pipelines' section and then enter the command `CTRL + F` nothing happens or if a file is open, the command opens a search in the file.

__Before Command:__
![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/107722987/a65b667f-aabc-4cc8-8541-abd4ec14049b)

__After Command:__
![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/107722987/5daeb91b-9331-4b44-ad41-50dcd350c725)

PS: thank you for this amazing extension!

**Comment by johnst101** [comment]
Hello, I have uninstalled and reinstalled the extension as well as restarting VS Code and it still doesn't show up with a search box when selecting CTRL + F.

**Comment by gbrueckl** [comment]
as mentioned in #30 , this is not related to this extension but to a generic change in VSCode which is described here https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding

**Comment by johnst101** [comment]
My apologies, I misunderstood the response. Very sorry, and thank you!
