### ISSUE TITLE
"Copy ID to Clipboard" for parameters of a Semantic model copies the name instead

### ISSUE THREAD

**Issue by tbobin** [gbrueckl/PowerBI-VSCode#34]
Rightclick "Copy ID to Clipboard" for a parameter in the Semantic model (Dataset), copy the name of the parameter instead of the ID

![image](https://github.com/user-attachments/assets/1cad677d-8f3c-4190-9b18-28b658adc6a8)

Or is the ID and the Name the same for parameters?

I'm using the PowerBI Studio v2.2.0

**Comment by gbrueckl** [comment]
parameters indeed do not have an ID hence the Name is copied
the `Copy X to Clipboard` actions are generic actions and can be used on any item - I did not implement any exceptions for items without IDs (e.g. parameters)
