### ISSUE TITLE
PPU Workspace but unable to perform any other dataset action other than "Update Parameters"

### ISSUE THREAD

**Issue by alexggrantham** [gbrueckl/PowerBI-VSCode#36]
My workspace resides in a PPU capacity but when I right click a dataset, hoping to see things like TMDL and memory statistics, I only get the option to update parameters.

![image](https://github.com/user-attachments/assets/78cbcfd2-9290-40f5-9a11-4f52990f318f)

**Comment by gbrueckl** [comment]
according to the screenshot it looks like you are using an old version of the extension - can you check?
please make sure to use the latest version `v2.4.0`

**Comment by alexggrantham** [comment]
Very sorry if I'm being dim but I don't know how to do that. The latest version available in VS Code is 0.98! Does the version of VS Code I'm running matter, I'm on 1.78.2?

![image](https://github.com/user-attachments/assets/d975d3e0-5263-41c1-87dc-e5e428eb6425)

![image](https://github.com/user-attachments/assets/991c3589-50a4-45b3-8e75-4223f6f392b7)

**Comment by gbrueckl** [comment]
looks like an issue with your mirror where VSCode checks for the extensions
you might want to try to download the `.vsix` directly from the gallery (https://marketplace.visualstudio.com/items?itemName=GerhardBrueckl.powerbi-vscode) and install it manually
