### ISSUE TITLE
Feature Request: Option to Retrigger a Previous Refresh from the Refreshes Folder

### ISSUE THREAD

**Issue by akhilannan** [gbrueckl/PowerBI-VSCode#38]
Currently, after refreshing specific tables from a dataset, I have to manually select those tables again and set refresh type, etc., to refresh them later. It would be extremely beneficial to have an option to retrigger a previously run refresh directly from the Refreshes folder of a dataset. 

**Right-click Context Menu:** Allow users to right-click on a refresh entry in the Refreshers folder and select "Retrigger" or "Refresh Again."

**Comment by gbrueckl** [comment]
while we cannot reconstruct the original refresh with its details (e.g. what was sent via the POST request), we could get the objects that have been processed and could resubmit a selective refresh for the objects provided in the selected refresh-run

however, things like "maxParallelism" or "retryCount" cannot be reused as the are not provided by the refresh-run anymore

**Comment by gbrueckl** [comment]
just released `v2.4.6` which also includes this feature :)
