### ISSUE TITLE
Expanding Workspace -> Dataflows does not work

### ISSUE THREAD

**Issue by tbobin** [gbrueckl/PowerBI-VSCode#7]
In some cases, the tree view does not show the dataflows of a workspace, with the following error: "Cannot read properties of undefined (reading 'toString')"

If I run an API call for this workspace I see  dataflows w/o a name and a description like:
```
    {
    "objectId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "configuredBy": "someone@example.com,
     "users": []
    },
```
It  seems to me that Datamarts have created these dataflows (at least I have only the issue with workspaces with Datamarts)

**Comment by tbobin** [comment]
I have the issue with the newest version v0.9.5
![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/21952673/d7125a71-da4c-4592-8f1b-be847d2e6454)

**Comment by gbrueckl** [comment]
ok, weird, then this is another issue 
and yes, as you already mentioned, probably related to datamarts

I will have a look

**Comment by gbrueckl** [comment]
will be fixed with the next release :)

**Comment by tbobin** [comment]
works with v0.9.6. 
thx
